### ISSUE TITLE
Wasn't sure who to contact..

### ISSUE THREAD

**Issue by jaddie** [jerronjames/sonarCF#1]
Hi,

I was just curious to know if this plugin has even been completed, it only seems to be a set of unit tests from what I can see?

Thanks
Jaddie

**Comment by jerronjames** [comment]
No, It was put on hold. If you’re looking for something to check ColdFusion, I would recommend CFLinthttps://github.com/cflint/CFLint It has a Jenkins plugin as well.

**Comment by caravela** [comment]
Just checking to see if this is a finished project yet.  When I try and use it, it throws errors during the sonarqube scan, then freezes.  

Thanks,
Matt

**Comment by jerronjames** [comment]
I just made a note on the readme that this project has been abandoned. Please consider https://github.com/CFLint.
